
import { Inter } from 'next/font/google'
import "./globals.css";
import Link from 'next/link';
import { TracingBeam } from '@/components/ui/tracing-beam';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap', 
})
 
export const metadata = {
  title: "RONY'S",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body
        className={` ${inter.className} antialiased p-8 selection:bg-slate-500`}
      >
       <nav className='flex justify-between   rounded  '>
        <h2>
         <Link href={`/`}>LOGO</Link>
        </h2>
        <ul className='flex gap-10'>
          <li className='inline-block cursor-pointer hover:text-slate-300 '> <Link href={`/home`}>Home</Link> </li>
          <li className='inline-block cursor-pointer hover:text-slate-300 '>About</li>
          <li className='inline-block cursor-pointer hover:text-slate-300 '>Enterprise</li>
          <li className='inline-block cursor-pointer hover:text-slate-300 '><Link href={`/gallery`}>Gallery</Link></li>
        </ul>
        <h2>
          Profile
        </h2>
        </nav>  
        <TracingBeam>

        {children}
        </TracingBeam>
      </body>
    </html>
  );
}
